import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Play, Sparkles, Terminal, CheckCircle2, XCircle, Copy, Check, ChevronDown, ChevronUp, AlertTriangle } from "lucide-react";
import { Button, Textarea, Badge } from "@/components/ui";
import { Sidebar } from "@/components/Sidebar";
import { useGenerateSql } from "@/hooks/use-sql-agent";
import { highlightSQL, cn } from "@/lib/utils";

const SAMPLE_QUERIES = [
  "Show me the top 5 customers by total order value this year",
  "Which products are low on stock and have been ordered in the last 30 days?",
  "List employees in the HR department with salary above average",
  "Monthly order revenue trend for the last 6 months",
];

export default function Home() {
  const [query, setQuery] = useState("");
  const [maxIterations, setMaxIterations] = useState(5);
  const [copied, setCopied] = useState(false);
  const [showLog, setShowLog] = useState(false);
  const [showFeedback, setShowFeedback] = useState(true);
  
  const bottomRef = useRef<HTMLDivElement>(null);

  const { mutate: generateSql, data: result, isPending, error } = useGenerateSql();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;
    generateSql({ query, max_iterations: maxIterations });
  };

  const handleCopy = () => {
    if (result?.sql) {
      navigator.clipboard.writeText(result.sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  useEffect(() => {
    if (result || error) {
      bottomRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  }, [result, error]);

  const getLogColor = (log: string) => {
    if (log.includes("[SchemaExtractor]")) return "text-purple-400";
    if (log.includes("[SQLGenerator]")) return "text-cyan-400";
    if (log.includes("[SQLValidator]")) {
      if (log.includes("PASSED")) return "text-success";
      if (log.includes("FAILED")) return "text-destructive";
      return "text-amber-400";
    }
    if (log.includes("ERROR")) return "text-destructive font-bold";
    return "text-slate-300";
  };

  return (
    <div className="flex flex-col md:flex-row h-screen w-full bg-background text-foreground overflow-hidden">
      
      {/* Main Content Area */}
      <div className="flex-1 flex flex-col overflow-y-auto relative custom-scrollbar">
        {/* Abstract Background Image generated by agent if available */}
        <div 
          className="absolute inset-0 z-0 opacity-[0.03] mix-blend-screen pointer-events-none"
          style={{ backgroundImage: `url(${import.meta.env.BASE_URL}images/abstract-bg.png)`, backgroundSize: 'cover', backgroundPosition: 'center' }}
        />

        <div className="flex-1 max-w-5xl mx-auto w-full p-4 md:p-8 flex flex-col gap-8 z-10">
          
          {/* Header */}
          <header className="flex flex-col gap-2 pt-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-lg shadow-primary/20">
                <Sparkles className="w-5 h-5 text-primary-foreground" />
              </div>
              <h1 className="text-3xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
                LangGraph SQL Agent
              </h1>
            </div>
            <p className="text-muted-foreground max-w-2xl text-sm">
              An intelligent, multi-agent pipeline that translates natural language into validated SAP HANA SQL. 
              It extracts schema, generates SQL, and loops to fix errors automatically.
            </p>
          </header>

          {/* Input Section */}
          <section className="bg-card/50 backdrop-blur-sm border border-border rounded-2xl p-6 shadow-xl relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary/50 via-accent to-transparent"></div>
            
            <form onSubmit={handleSubmit} className="flex flex-col gap-4">
              <div className="space-y-2">
                <label className="text-sm font-medium text-slate-300 flex justify-between">
                  <span>What data do you need?</span>
                </label>
                <Textarea
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="e.g. Which products are low on stock and have been ordered in the last 30 days?"
                  className="min-h-[120px] text-base resize-none bg-background/50 border-border/50 focus:border-primary/50 font-sans"
                  disabled={isPending}
                />
              </div>

              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <label className="text-xs text-muted-foreground whitespace-nowrap">Max Iterations:</label>
                  <div className="flex items-center bg-background/50 rounded-md border border-border/50 overflow-hidden">
                    {[3, 5, 8, 10].map(val => (
                      <button
                        key={val}
                        type="button"
                        onClick={() => setMaxIterations(val)}
                        disabled={isPending}
                        className={cn(
                          "px-3 py-1 text-xs font-medium transition-colors",
                          maxIterations === val 
                            ? "bg-primary text-primary-foreground" 
                            : "text-muted-foreground hover:bg-accent/50 hover:text-foreground"
                        )}
                      >
                        {val}
                      </button>
                    ))}
                  </div>
                </div>

                <Button 
                  type="submit" 
                  size="lg" 
                  disabled={!query.trim() || isPending}
                  className="w-full sm:w-auto relative group overflow-hidden"
                >
                  {isPending ? (
                    <>
                      <div className="absolute inset-0 bg-primary/20 animate-pulse"></div>
                      <div className="flex items-center gap-2 relative z-10">
                        <Terminal className="w-4 h-4 animate-bounce" />
                        <span>Agents Thinking...</span>
                      </div>
                    </>
                  ) : (
                    <div className="flex items-center gap-2">
                      <Play className="w-4 h-4 fill-current" />
                      <span>Generate SQL</span>
                    </div>
                  )}
                </Button>
              </div>
            </form>

            {/* Sample Queries */}
            <div className="mt-6 pt-4 border-t border-border/50">
              <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-3">Try a sample query</p>
              <div className="flex flex-wrap gap-2">
                {SAMPLE_QUERIES.map((sq, i) => (
                  <button
                    key={i}
                    onClick={() => setQuery(sq)}
                    disabled={isPending}
                    className="text-xs text-left px-3 py-1.5 rounded-full border border-border/50 bg-secondary/30 text-slate-300 hover:bg-secondary hover:text-white transition-colors max-w-full truncate"
                  >
                    {sq}
                  </button>
                ))}
              </div>
            </div>
          </section>

          {/* Results Section */}
          <AnimatePresence mode="wait">
            {error && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95 }}
                className="bg-destructive/10 border border-destructive/20 rounded-xl p-6 flex gap-4 items-start"
              >
                <XCircle className="w-6 h-6 text-destructive shrink-0 mt-0.5" />
                <div>
                  <h3 className="text-destructive font-semibold">Pipeline Error</h3>
                  <p className="text-sm text-destructive/80 mt-1">{error.message}</p>
                </div>
              </motion.div>
            )}

            {isPending && !result && (
              <motion.div 
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center py-16 space-y-4"
              >
                <div className="relative w-16 h-16 flex items-center justify-center">
                  <div className="absolute inset-0 rounded-full border-t-2 border-primary animate-spin"></div>
                  <div className="absolute inset-2 rounded-full border-r-2 border-accent animate-spin animation-delay-150"></div>
                  <Sparkles className="w-6 h-6 text-primary animate-pulse" />
                </div>
                <div className="text-center">
                  <p className="text-primary font-medium animate-pulse">Running Multi-Agent Loop...</p>
                  <p className="text-xs text-muted-foreground mt-1">Extracting schema → Generating SQL → Validating</p>
                </div>
              </motion.div>
            )}

            {result && !isPending && (
              <motion.div 
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                className="flex flex-col gap-6"
              >
                {/* Result Header */}
                <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-card border border-border rounded-xl shadow-md">
                  <div className="flex items-center gap-3">
                    {result.passed ? (
                      <Badge variant="success" className="px-3 py-1 text-sm flex items-center gap-1.5">
                        <CheckCircle2 className="w-4 h-4" /> Passed Validation
                      </Badge>
                    ) : (
                      <Badge variant="warning" className="px-3 py-1 text-sm flex items-center gap-1.5">
                        <AlertTriangle className="w-4 h-4" /> Best Effort (Failed Validation)
                      </Badge>
                    )}
                    <span className="text-sm text-muted-foreground font-medium">
                      Completed in <span className="text-foreground">{result.iterations}</span> iteration(s)
                    </span>
                  </div>
                  
                  <Button variant="secondary" size="sm" onClick={handleCopy} className="gap-2">
                    {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
                    {copied ? "Copied!" : "Copy SQL"}
                  </Button>
                </div>

                {/* SQL Code Block */}
                <div className="rounded-xl overflow-hidden border border-border shadow-2xl bg-[#0d1117] relative">
                  <div className="flex items-center px-4 py-2 bg-slate-900 border-b border-border/50 text-xs font-mono text-slate-400">
                    <Terminal className="w-3 h-3 mr-2" /> generated_query.sql
                  </div>
                  <div className="p-4 md:p-6 overflow-x-auto text-sm md:text-base font-mono leading-relaxed custom-scrollbar">
                    <pre><code dangerouslySetInnerHTML={{ __html: highlightSQL(result.sql) }} /></pre>
                  </div>
                </div>

                {/* Feedback Section (if failed) */}
                {result.feedback && (
                  <div className="bg-warning/5 border border-warning/20 rounded-xl overflow-hidden">
                    <button 
                      onClick={() => setShowFeedback(!showFeedback)}
                      className="w-full flex items-center justify-between p-4 hover:bg-warning/10 transition-colors"
                    >
                      <div className="flex items-center gap-2 text-warning">
                        <AlertTriangle className="w-5 h-5" />
                        <span className="font-semibold">Validator Feedback</span>
                      </div>
                      {showFeedback ? <ChevronUp className="w-4 h-4 text-warning" /> : <ChevronDown className="w-4 h-4 text-warning" />}
                    </button>
                    
                    <AnimatePresence>
                      {showFeedback && (
                        <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} className="overflow-hidden">
                          <div className="p-4 pt-0 border-t border-warning/10">
                            <pre className="text-xs text-warning/80 whitespace-pre-wrap font-mono bg-black/20 p-4 rounded-lg mt-2">
                              {result.feedback}
                            </pre>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                )}

                {/* Agent Log Terminal */}
                <div className="bg-black/50 border border-border rounded-xl overflow-hidden mb-12 shadow-inner">
                  <button 
                    onClick={() => setShowLog(!showLog)}
                    className="w-full flex items-center justify-between p-3 bg-card hover:bg-secondary/50 transition-colors border-b border-border"
                  >
                    <div className="flex items-center gap-2">
                      <Terminal className="w-4 h-4 text-slate-400" />
                      <span className="text-sm font-semibold text-slate-200">Agent Pipeline Trace</span>
                      <Badge variant="outline" className="ml-2 text-[10px] bg-background">{result.agent_log.length} events</Badge>
                    </div>
                    {showLog ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
                  </button>
                  
                  <AnimatePresence>
                    {showLog && (
                      <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} className="overflow-hidden">
                        <div className="p-4 space-y-1.5 font-mono text-xs max-h-[400px] overflow-y-auto custom-scrollbar">
                          {result.agent_log.map((log, i) => (
                            <div key={i} className={cn("whitespace-pre-wrap break-words border-l-2 pl-3 py-0.5", 
                              log.includes("[SchemaExtractor]") ? "border-purple-500/50 bg-purple-500/5" :
                              log.includes("[SQLGenerator]") ? "border-cyan-500/50 bg-cyan-500/5" :
                              log.includes("[SQLValidator]") ? "border-amber-500/50 bg-amber-500/5" : "border-slate-700"
                            )}>
                              <span className={getLogColor(log)}>{log}</span>
                            </div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
                
              </motion.div>
            )}
          </AnimatePresence>
          <div ref={bottomRef} className="h-4"></div>
        </div>
      </div>

      {/* Sidebar */}
      <Sidebar />
    </div>
  );
}
